"""add budget items

Revision ID: 28889230d4ca
Revises: f4ac99e82426
Create Date: 2026-07-09 18:34:59.079525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28889230d4ca'
down_revision = 'f4ac99e82426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_items')
    # ### end Alembic commands ###
