"""add entry type to contributions

Revision ID: 6fadd6173f3f
Revises: f316ce0f5347
Create Date: 2026-07-05 19:53:23.222235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fadd6173f3f'
down_revision = 'f316ce0f5347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_type', sa.String(length=20), server_default='deposit', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_column('entry_type')

    # ### end Alembic commands ###
