"""add retailer prices

Revision ID: c6ab77c31f04
Revises: 28889230d4ca
Create Date: 2026-07-09 19:15:32.162316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ab77c31f04'
down_revision = '28889230d4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('retailer_name', sa.String(length=120), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), server_default='0', nullable=False),
    sa.Column('tax_estimate', sa.Float(), server_default='0', nullable=False),
    sa.Column('is_preferred', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retailer_prices')
    # ### end Alembic commands ###
