"""add retailer to goals

Revision ID: f316ce0f5347
Revises: 7f9b8b77bef6
Create Date: 2026-07-05 19:06:20.166755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f316ce0f5347'
down_revision = '7f9b8b77bef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('retailer')

    # ### end Alembic commands ###
