"""add profile fields to users

Revision ID: f4ac99e82426
Revises: 2dd6b50c9934
Create Date: 2026-07-09 18:21:01.251339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ac99e82426'
down_revision = '2dd6b50c9934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('monthly_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('monthly_budget')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
